# -*- coding: utf-8 -*-
"""projeto_Smart_City_Laguna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tINY4YufFgB-jFBUGrxd5jLq5F6Ga88A

Análise e Otimização do Consumo de Energia Residencial por Ambiente

1. Introdução

Objetivo:

entender o consumo de energia elétrica em residências dividido por cômodos e identificar padrões para otimizar uso e reduzir desperdícios.

Importância:

energia é um dos maiores custos fixos, e uma gestão eficiente traz economia financeira e ambiental.

Dados:

consumo diário por cômodo (quartos, sala, cozinha, piscina) e consumo total (KW/H) em 211 dias.

2. Metodologia


Análise exploratória:

estudamos dados de consumo por cômodo, identificando médias, variações e perfis típicos.

Clusterização:

agrupamos residências em clusters de consumo (baixo, equilibrado, alto) para personalizar recomendações.

Modelagem preditiva:

construímos um modelo de regressão linear para prever o consumo total a partir do consumo individual de cada cômodo.

Avaliação:

medimos desempenho do modelo com métricas MAE e R² para garantir previsões confiáveis.

Recomendações:

baseadas nos clusters, sugerimos ações práticas para cada perfil.

3. Resultados e Análise

Clusterização:

identificamos 3 grupos principais:

Baixo consumo — residências com consumo controlado e eficiente.

Consumo equilibrado — consumo médio com algumas áreas elevadas.

Alto consumo — consumo elevado, especialmente em sala, cozinha ou piscina.

Modelo de regressão linear: R² de 0,86 indica alta capacidade preditiva.

Sala tem maior impacto no consumo total.

Análise temporal:

identificamos picos e sazonalidades para futuras intervenções programadas.

4. Conclusões de Ciência de Dados


Os dados possibilitaram segmentar residências e prever consumo com alta precisão.

O modelo é simples, interpretável e indica os cômodos que mais influenciam o consumo total.

A análise permitiu criar perfis que facilitam recomendações direcionadas.

5. Impacto de Negócio e Recomendações


Com base nos clusters, o cliente pode oferecer planos personalizados, descontos e incentivos para reduzir consumo.

Sugestões incluem automação, sensores de presença, uso consciente e tarifas diferenciadas.

A abordagem pode reduzir custos e aumentar satisfação do cliente, além de contribuir para sustentabilidade.
"""

import pandas as pd
import locale
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

# Carregar o arquivo Excel com múltiplas abas
file_path = "Consumo_de_Energia_Analise.xlsx"
xls = pd.ExcelFile(file_path)

# Listar os nomes das abas
sheet_names = xls.sheet_names
sheet_names

# Carregar os dados da aba "Sheet1"
df = xls.parse('Sheet1')

# Exibir as primeiras linhas para análise inicial
df

df.info()

# Mapeamento de abreviações de meses em português para números
meses_pt = {
    'jan': '01', 'fev': '02', 'mar': '03', 'abr': '04',
    'mai': '05', 'jun': '06', 'jul': '07', 'ago': '08',
    'set': '09', 'out': '10', 'nov': '11', 'dez': '12'
}

# Converter datas de '01/jan' para '01/01/2025'
df['Data'] = df['Data'].str.lower().replace(meses_pt, regex=True)
df['Data'] = pd.to_datetime(df['Data'] + '/2025', format='%d/%m/%Y')

# Estatísticas descritivas
summary = df.describe()

# Correlação entre as variáveis
correlation = df.corr(numeric_only=True)

# Visualização: histograma das variáveis
fig, axes = plt.subplots(nrows=2, ncols=3, figsize=(16, 8))
axes = axes.flatten()
for i, col in enumerate(df.columns[1:]):  # Ignora a coluna 'Data'
    sns.histplot(df[col], kde=True, ax=axes[i], bins=10)
    axes[i].set_title(f'Distribuição - {col}')
    axes[i].set_xlabel(col)

plt.tight_layout()
plt.suptitle("Distribuição das Variáveis de Consumo", fontsize=16, y=1.02)
plt.show()

summary, correlation

"""📈 Resumo Estatístico das Variáveis
Média de consumo diário: 1188,3 kWh

Máximo: 1667 kWh, Mínimo: 644 kWh

Cômodos mais acionados:

Quarto1: média de 9,7 vezes/dia

Cozinha e Piscina: ~9,3 vezes/dia

Sala tem a maior variação de uso (até 17 vezes/dia)

Os dados estão bem distribuídos — sem grandes distorções ou outliers evidentes.

📊 Correlação com o consumo total (KW/H):
Sala tem a maior correlação com o consumo total: 0.55

Depois vêm Quarto1 (0.52) e Piscina (0.43)

Quarto2 e Cozinha também influenciam, mas com menor peso.

A Cozinha tem correlação negativa com a Piscina (-0.08), sugerindo uso alternado em alguns dias.

🧠 Insights de Ciência de Dados + Negócio
Você pode construir um modelo de regressão linear para prever o consumo com base nas ativações por cômodo.

Uma clusterização K-means também pode separar dias em grupos de uso leve, moderado e intenso — ótimo para personalizar alertas ou otimizar tarifas.

Do ponto de vista ESG e Smart City, esses dados podem orientar:

Campanhas educativas por cômodo (ex: “Uso consciente da sala”)

Automação via IoT (ex: alertas quando uso da piscina exceder padrão)
"""

# Plotar consumo total ao longo do tempo
plt.figure(figsize=(14, 6))
plt.plot(df['Data'], df['KW/H'], label='Consumo Total (KW/H)', color='blue', linewidth=2)
plt.title('Evolução do Consumo Total de Energia')
plt.xlabel('Data')
plt.ylabel('KW/H')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# Agora plotar o consumo por cômodo no mesmo gráfico, para comparar
plt.figure(figsize=(16, 8))
for comodo in ['Quarto1', 'Quarto2', 'Sala', 'Cozinha', 'Piscina']:
    plt.plot(df['Data'], df[comodo], label=comodo)

plt.title('Consumo de Energia por Cômodo ao Longo do Tempo')
plt.xlabel('Data')
plt.ylabel('Consumo')
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

# Definir variáveis preditoras (X) e variável alvo (y)
X = df[['Quarto1', 'Quarto2', 'Sala', 'Cozinha', 'Piscina']]
y = df['KW/H']

# Separar treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Regressão linear
modelo = LinearRegression()
modelo.fit(X_train, y_train)

# Predição
y_pred = modelo.predict(X_test)

# Avaliação do modelo
print("Coeficientes:", modelo.coef_)
print("Intercepto:", modelo.intercept_)
print("Erro médio absoluto (MAE):", mean_absolute_error(y_test, y_pred))
print("R² (coeficiente de determinação):", r2_score(y_test, y_pred))

"""📌 Resultados do Modelo

✅ Coeficientes:

Sala: +25.79 → maior impacto no consumo total

Piscina: +24.45

Cozinha: +23.49

Quarto1 / Quarto2: também relevantes, cerca de +23.3 e +23.1

Isso indica que cada vez que um ambiente é utilizado, o consumo estimado aumenta cerca de 23 a 26 kWh, com a sala sendo a mais impactante.

🎯 Intercepto:

49.88 kWh: o consumo base estimado mesmo com zero ativações — pode refletir consumo contínuo (geladeiras, standby etc.)

📉 Erro Médio Absoluto (MAE):

57.74 kWh → baixo em relação à média total (~1188 kWh), indicando boa precisão.

📈 R² (Coeficiente de determinação):

0.86 → o modelo explica 86% da variação no consumo, um valor muito bom para aplicações práticas.


"""

plt.scatter(y_test, y_pred, alpha=0.7)
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--')  # Linha identidade
plt.xlabel('Consumo Real (KW/H)')
plt.ylabel('Consumo Previsto (KW/H)')
plt.title('Real vs Previsto - Consumo Total')
plt.show()

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns

# Dados usados na clusterização
X = df[['Quarto1', 'Quarto2', 'Sala', 'Cozinha', 'Piscina']]

# Normalização (fundamental para KMeans)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Encontrar número ideal de clusters (opcional)
inertia = []
for k in range(1, 10):
    km = KMeans(n_clusters=k, random_state=42)
    km.fit(X_scaled)
    inertia.append(km.inertia_)

plt.plot(range(1, 10), inertia, marker='o')
plt.title('Método do Cotovelo')
plt.xlabel('Número de clusters')
plt.ylabel('Inércia')
plt.show()

# Aplicar KMeans com 3 clusters (ajuste conforme o gráfico do cotovelo)
kmeans = KMeans(n_clusters=3, random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

# Visualização
sns.pairplot(df, hue='Cluster', vars=['Quarto1', 'Quarto2', 'Sala', 'Cozinha', 'Piscina'], palette='tab10')
plt.suptitle("Padrões de Uso Agrupados por Cluster", y=1.02)
plt.show()

# === PERFIL DE CADA CLUSTER ===
perfil_clusters = df.groupby('Cluster')[['Quarto1', 'Quarto2', 'Sala', 'Cozinha', 'Piscina', 'KW/H']].mean()

def nomear_cluster(row):
    media_kw = df['KW/H'].mean()

    # Consumo total
    if row['KW/H'] < media_kw * 0.75:
        consumo_total = '🔵 Baixo Consumo'
    elif row['KW/H'] > media_kw * 1.25:
        consumo_total = '🔴 Alto Consumo'
    else:
        consumo_total = '🟡 Consumo Equilibrado'

    # Verificar cômodos com consumo alto
    altos = []
    for comodo in ['Quarto1', 'Quarto2', 'Sala', 'Cozinha', 'Piscina']:
        if row[comodo] > df[comodo].mean() * 1.2:  # 20% acima da média daquele cômodo
            altos.append(comodo)

    # Montar nome do cluster com base nos cômodos de alto consumo
    if consumo_total == '🔵 Baixo Consumo':
        return consumo_total

    if consumo_total == '🟡 Consumo Equilibrado' and len(altos) == 0:
        return consumo_total

    if consumo_total == '🟡 Consumo Equilibrado' and len(altos) > 0:
        return f"🟠 Consumo Elevado em {', '.join(altos)}"

    if consumo_total == '🔴 Alto Consumo':
        if len(altos) == 0:
            return consumo_total
        else:
            return f"🔴 Alto Consumo (Em {', '.join(altos)})"

perfil_clusters['Perfil'] = perfil_clusters.apply(nomear_cluster, axis=1)

# Mapeamento para chaves base do dicionário recomendacoes
def mapear_perfil_para_chave(perfil):
    if perfil == '🔵 Baixo Consumo':
        return perfil
    if perfil == '🟡 Consumo Equilibrado':
        return perfil
    if perfil.startswith('🟠 Consumo Elevado'):
        # Aqui você pode escolher um nome genérico ou identificar cômodo específico
        # Por exemplo, se só quiser geral:
        return '🟠 Consumo Elevado'
    if perfil.startswith('🔴 Alto Consumo'):
        # Pode mapear por cômodos mais frequentes ou usar geral
        # Vamos tentar diferenciar por cômodo principal (primeiro da lista)
        # Exemplo de extração do primeiro cômodo:
        import re
        encontrados = re.findall(r'\b\w+\b', perfil)  # pega palavras
        # Pegando o primeiro cômodo após "Em"
        if 'Em' in perfil:
            idx = perfil.index('Em') + 3
            # extrair o texto depois de "Em "
            texto = perfil[idx:]
            principal = texto.split(',')[0].strip()
            if principal == 'Sala' or principal == 'Piscina':
                return '🔴 Alto Consumo (Sala/Piscina)'
            elif principal == 'Cozinha':
                return '🔴 Alto Consumo (Cozinha)'
            else:
                return '🔴 Alto Consumo'
        else:
            return '🔴 Alto Consumo'
    return perfil  # fallback

recomendacoes = {
    '🔵 Baixo Consumo': [
        "✅ Manter boas práticas já adotadas.",
        "🎁 Oferecer recompensas ou descontos (gamificação).",
        "🔋 Incentivar uso de energia solar / microgeração."
    ],
    '🟡 Consumo Equilibrado': [
        "🔌 Automatizar desligamento de equipamentos em horários fixos.",
        "🕵️ Instalar sensores de presença em quartos e sala.",
        "📊 Enviar relatórios semanais de uso comparativo."
    ],
    '🟠 Consumo Elevado': [
        "🛏️ Automatizar luzes e eletrônicos nos cômodos com consumo elevado.",
        "🕵️ Instalar sensores de presença específicos para os cômodos.",
        "📊 Acompanhar o uso para identificar picos desnecessários."
    ],
    '🔴 Alto Consumo (Sala/Piscina)': [
        "💧 Agendar funcionamento da bomba da piscina fora do pico.",
        "💡 Incentivar uso consciente da iluminação e eletrônicos.",
        "🧠 Sugerir automação e adesão à tarifa branca."
    ],
    '🔴 Alto Consumo (Cozinha)': [
        "🍳 Verificar equipamentos de cozinha para consumo excessivo.",
        "⏰ Controlar horários de uso de forno e geladeira.",
        "💡 Incentivar uso eficiente da iluminação."
    ]
}

# Exibir os perfis e recomendações
for cluster_id, row in perfil_clusters.iterrows():
    print(f"\n=== Cluster {cluster_id} - {row['Perfil']} ===")
    print("📊 Perfil médio:")
    print(row[['Quarto1', 'Quarto2', 'Sala', 'Cozinha', 'Piscina', 'KW/H']])
    print("\n💡 Recomendações:")

    chave = mapear_perfil_para_chave(row['Perfil'])

    if chave in recomendacoes:
        for item in recomendacoes[chave]:
            print("-", item)
    else:
        print("- Sem recomendações específicas para este perfil.")

"""# Relatório de Perfis de Consumo por Cluster

---

## === Cluster 0 - 🟡 Consumo Equilibrado ===

### 📊 Perfil médio:
| Ambiente  | Consumo Médio (kWh) |
| --------- | ------------------- |
| Quarto1   | 10.00               |
| Quarto2   | 11.19               |
| Sala      | 8.25                |
| Cozinha   | 8.89                |
| Piscina   | 6.93                |
| **Total (KW/H)** | **1129.99**      |

### 💡 Recomendações:
- 🔌 Automatizar desligamento de equipamentos em horários fixos.
- 🕵️ Instalar sensores de presença em quartos e sala.
- 📊 Enviar relatórios semanais de uso comparativo.

---

## === Cluster 1 - 🟠 Consumo Elevado em Sala, Cozinha ===

### 📊 Perfil médio:
| Ambiente  | Consumo Médio (kWh) |
| --------- | ------------------- |
| Quarto1   | 11.46               |
| Quarto2   | 9.74                |
| Sala      | 12.51               |
| Cozinha   | 11.23               |
| Piscina   | 9.89                |
| **Total (KW/H)** | **1368.13**      |

### 💡 Recomendações:
- 🛏️ Automatizar luzes e eletrônicos nos cômodos com consumo elevado.
- 🕵️ Instalar sensores de presença específicos para os cômodos.
- 📊 Acompanhar o uso para identificar picos desnecessários.

---

## === Cluster 2 - 🟠 Consumo Elevado em Piscina ===

### 📊 Perfil médio:
| Ambiente  | Consumo Médio (kWh) |
| --------- | ------------------- |
| Quarto1   | 7.93                |
| Quarto2   | 7.76                |
| Sala      | 8.15                |
| Cozinha   | 8.20                |
| Piscina   | 11.43               |
| **Total (KW/H)** | **1100.40**      |

### 💡 Recomendações:
- 💧 Monitorar o uso da piscina e bombas.
- ⏰ Programar horários eficientes para funcionamento.
- 💡 Incentivar uso consciente da iluminação externa.

---

*Fim do relatório.*

"""